name: سوال پشتیبانی
description: برای نحوه استفاده از ما کمک بخواهید
title: "[پشتیبانی]: "
labels: ["api-usage"]
body:
  - type: markdown
    attributes:
      value: |
        **توجه:** قبل از ثبت مورد جدید [مستندات مربوطه](https://apidocs.nobitex.ir/) و [موردهای قدیمی پشتیبانی](https://github.com/nobitex/docs-api/issues?q=is%3Aissue+label%3Aapi-usage) را بخوانید. در صورت یافتن مورد مشابه همانجا مسئله خود را مطرح کنید
  - type: textarea
    id: goal
    attributes:
      label: هدف
      description: |
        به طور اجمالی شرح دهید می‌خواهید چه کاری از طریق نوبیتکس انجام دهید:
      placeholder: |
        مثلا: ثبت سفارش خرید دوج کوین به قیمت بازار
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: محیط درخواست
      description: |
        ویژگی‌های موثر در درخواست را طبق مستندات آن ارائه کنید:
      placeholder: |
        - ابزار درخواست (مرورگر/ابزار/برنامه/...)
        - زبان برنامه (cURL/Python/PHP/...)
        - محل درخواست (local/VPS/...)
        - درخواست IP (داخلی/خارجی)
        - ...
      value: |
        - ابزار درخواست (مرورگر/ابزار/برنامه/...)
        - زبان برنامه (cURL/Python/PHP/...)
        - محل درخواست (local/VPS/...)
        - درخواست IP (داخلی/خارجی)
        - ...
  - type: textarea
    id: request
    attributes:
      label: نحوه درخواست
      description: |
        کد مورد استفاده خود را ضمیمه کنید:
        این بخش از کد باید شامل اطلاعات زیر باشد:  1. آدرس  2. داده  3. هدر  4. محیط (آدرس پایه)
        داده‌های حساس خود مانند توکن هویت یا شناسه سفارشات را با * مخدوش نمایید
      placeholder: |
        مثلا:
        ```python
        import requests
        url = 'https://apiv2.nobitex.ir/market/orders/add'
        headers = {'Authorization': 'Token abt*********************xz'}
        data = {'srcCurrency': 'doge', 'type': 'buy', 'execution': 'market', ...}
        response = requests.post(url, json=data, headers=headers)
        print(response.json())
        ```
    validations:
      required: true
  - type: textarea
    id: response
    attributes:
      label: پاسخ دریافتی
      description: |
        پیغام خطای نوبیتکس را در اینجا درج کنید:
      placeholder: |
        ```{"status": "failed", "code": "SampleCode",...}```
    validations:
      required: true
  - type: textarea
    id: additional-data
    attributes:
      label: اطلاعات تکمیلی
      description: |
        هر اطلاعات دیگری که برای کشف ریشه مشکل می‌تواند به ما کمک کند در اینجا ضمیمه کنید:
