name: Deploy Docusaurus

on:
  push:
    branches: [ 'main/open-api' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Clean old docs
      run: yarn clean:docs

    - name: Generate API docs
      run: yarn genapi

    - name: Build site
      run: yarn build

    - name: Deploy to GitHub Pages
      run: yarn deploy
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}